"""initial schema

Revision ID: faf6ec377bde
Revises: 
Create Date: 2026-08-18 08:19:03.435247+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'XIAOHONGSHU', name='platform'), nullable=False),
    sa.Column('default_language', sa.Enum('KO', 'ZH', 'EN', name='language'), nullable=False),
    sa.Column('brand_voice_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active_style_dna_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_style_dna_id'], ['style_dna.id'], name='fk_account_active_style_dna', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_handle'), ['handle'], unique=True)
        batch_op.create_index(batch_op.f('ix_account_platform'), ['platform'], unique=False)

    op.create_table('style_dna',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('SCREENSHOTS', 'URL', 'MANUAL', name='stylesourcetype'), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('dna', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style_dna', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_dna_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_style_dna_is_active'), ['is_active'], unique=False)

    op.create_table('topic_brief',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_input_type', sa.Enum('DOCUMENT', 'CHAT', 'KEYWORD', 'PROPOSED', name='topicinputtype'), nullable=False),
    sa.Column('raw_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('normalized', sa.JSON(), nullable=False),
    sa.Column('proposed_by_system', sa.Boolean(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic_brief', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_brief_account_id'), ['account_id'], unique=False)

    op.create_table('carousel_set',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('style_dna_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('topic_brief_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'XIAOHONGSHU', name='platform'), nullable=False),
    sa.Column('language', sa.Enum('KO', 'ZH', 'EN', name='language'), nullable=False),
    sa.Column('slide_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATING', 'QA', 'READY', 'PUBLISHED', 'ARCHIVED', name='setstatus'), nullable=False),
    sa.Column('caption', sa.JSON(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('quality_report', sa.JSON(), nullable=False),
    sa.Column('fact_report', sa.JSON(), nullable=False),
    sa.Column('parent_set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('variant_type', sa.Enum('ORIGINAL', 'TRANSLATION', 'RESTYLE', name='varianttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['parent_set_id'], ['carousel_set.id'], ),
    sa.ForeignKeyConstraint(['style_dna_id'], ['style_dna.id'], ),
    sa.ForeignKeyConstraint(['topic_brief_id'], ['topic_brief.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carousel_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carousel_set_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carousel_set_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_carousel_set_parent_set_id'), ['parent_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carousel_set_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_carousel_set_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_carousel_set_style_dna_id'), ['style_dna_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carousel_set_topic_brief_id'), ['topic_brief_id'], unique=False)

    op.create_table('asset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sa.Enum('BACKGROUND', 'RENDER', 'EXPORT_SVG', 'EXPORT_ZIP', 'PREVIEW', name='assetkind'), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mime', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('generation_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('is_discarded', sa.Boolean(), nullable=False),
    sa.Column('discard_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['carousel_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_is_discarded'), ['is_discarded'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_set_id'), ['set_id'], unique=False)

    op.create_table('fact_check',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=True),
    sa.Column('claim', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verdict', sa.Enum('VERIFIED', 'UNVERIFIED', 'DISPUTED', 'FALSE', name='factverdict'), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['carousel_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fact_check', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_check_set_id'), ['set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_check_verdict'), ['verdict'], unique=False)

    op.create_table('generation_log',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Enum('INTAKE', 'STYLE_RESOLVE', 'RESEARCH', 'FACTCHECK', 'ARCHITECT', 'COPY', 'VISUAL_GEN', 'COMPOSE', 'QUALITY_GATE', 'LOCALIZE', 'EXPORT', 'PERSIST', name='pipelinestage'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Enum('PASS', 'WARN', 'DISCARD', 'FAIL', name='generationverdict'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['carousel_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_log_set_id'), ['set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_log_stage'), ['stage'], unique=False)

    op.create_table('slide',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('HOOK', 'CONTEXT', 'POINT', 'PROOF', 'EXAMPLE', 'SUMMARY', 'CTA', name='sliderole'), nullable=False),
    sa.Column('layout_template', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('background_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('copy_blocks', sa.JSON(), nullable=False),
    sa.Column('render_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('svg_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['background_asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['render_asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['carousel_set.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_id', 'index', name='uq_slide_set_index')
    )
    with op.batch_alter_table('slide', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slide_set_id'), ['set_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slide', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slide_set_id'))

    op.drop_table('slide')
    with op.batch_alter_table('generation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_log_stage'))
        batch_op.drop_index(batch_op.f('ix_generation_log_set_id'))

    op.drop_table('generation_log')
    with op.batch_alter_table('fact_check', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_check_verdict'))
        batch_op.drop_index(batch_op.f('ix_fact_check_set_id'))

    op.drop_table('fact_check')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_set_id'))
        batch_op.drop_index(batch_op.f('ix_asset_kind'))
        batch_op.drop_index(batch_op.f('ix_asset_is_discarded'))

    op.drop_table('asset')
    with op.batch_alter_table('carousel_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carousel_set_topic_brief_id'))
        batch_op.drop_index(batch_op.f('ix_carousel_set_style_dna_id'))
        batch_op.drop_index(batch_op.f('ix_carousel_set_status'))
        batch_op.drop_index(batch_op.f('ix_carousel_set_platform'))
        batch_op.drop_index(batch_op.f('ix_carousel_set_parent_set_id'))
        batch_op.drop_index(batch_op.f('ix_carousel_set_language'))
        batch_op.drop_index(batch_op.f('ix_carousel_set_account_id'))

    op.drop_table('carousel_set')
    with op.batch_alter_table('topic_brief', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_brief_account_id'))

    op.drop_table('topic_brief')
    with op.batch_alter_table('style_dna', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_dna_is_active'))
        batch_op.drop_index(batch_op.f('ix_style_dna_account_id'))

    op.drop_table('style_dna')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_platform'))
        batch_op.drop_index(batch_op.f('ix_account_handle'))

    op.drop_table('account')
    # ### end Alembic commands ###
